[package]
name = "guessing_game_v3"
version = "0.1.0"
authors = ["saura8h"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.7.0"
